[package]
name = "tablet-pc-rotation"
version = "0.1.0"
authors = ["DjebbZ <khalid.jebbari@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
